---
- get_interfaces:
    Ethernet0/0:
      description: OOB Management
      is_enabled: true
      is_up: true
      speed: 10
    Ethernet0/1:
      description: To Internet
      is_enabled: true
      is_up: true
      speed: 10
    Ethernet0/2:
      description: To lab-arista-01 - Ethernet2
      is_enabled: true
      is_up: true
      speed: 10
    Ethernet0/3:
      description: To lab-iosv-02 - Ethernet0/3
      is_enabled: true
      is_up: true
      speed: 10
    Loopback0:
      description: Loopback Interface
      is_enabled: true
      is_up: true
      speed: 8000
- get_interfaces_ip:
    Ethernet0/0:
      ipv4:
        10.0.0.12:
          prefix_length: 24
    Ethernet0/1:
      ipv4:
        192.168.11.12:
          prefix_length: 24
    Ethernet0/2:
      ipv4:
        192.168.30.9:
          prefix_length: 30
    Ethernet0/3:
      ipv4:
        192.168.30.5:
          prefix_length: 30
    Loopback0:
      ipv4:
        192.168.40.12:
          prefix_length: 32
