---
- get_bgp_neighbors:
    global:
      peers:
        192.168.11.1:
          address_family:
            ipv4:
              accepted_prefixes: 4
              received_prefixes: 4
              sent_prefixes: 6
          description: dfjt-r001
          is_enabled: true
          is_up: true
          local_as: 65013
          remote_as: 65001
          remote_id: 192.168.40.1
        192.168.30.2:
          address_family:
            ipv4:
              accepted_prefixes: 3
              received_prefixes: 3
              sent_prefixes: 6
          description: lab-nxos-01
          is_enabled: true
          is_up: true
          local_as: 65013
          remote_as: 65014
          remote_id: 192.168.40.14
        192.168.30.5:
          address_family:
            ipv4:
              accepted_prefixes: 5
              received_prefixes: 5
              sent_prefixes: 6
          description: lab-iosv-01
          is_enabled: true
          is_up: true
          local_as: 65013
          remote_as: 65012
          remote_id: 192.168.40.12
      router_id: 192.168.40.13
