---
language: python
python:
  - "2.7"
  - "3.6"
  - "3.7"
install:
  - pip install ansible-lint
  - ansible-lint --version
  - pip install yamllint
  - yamllint --version
jobs:
  include:
    - stage: yaml-lint
      name: yamllint playbooks
      script: yamllint 5_Logging_Testing_Validation/ansible/*data-model*.yml
    - stage: ansible-lint
      name: ansible-linting playbooks
      script: yamllint 5_Logging_Testing_Validation/ansible/data-model-validate.yml
