---
language: python
install:
  - pip install ansible-lint
  - ansible-lint --version
  - pip install yamllint
  - yamllint --version
  - pip install napalm-ansible
  - napalm-ansible --version
jobs:
  include:
    - stage: yaml-lint
      name: yamllint-playbooks-1
      script: yamllint 5_Logging_Testing_Validation/ansible/*data-model*.yml
    - stage: ansible-lint
      name: ansible-linting-playbooks-2
      script:
        - cd 5_Logging_Testing_Validation/ansible/     
        - ansible-lint *data-model*.yml
