---
- name: Compiled automated validation files
  hosts: all
  connection: local
  vars:
    validate_dir: "{{ playbook_dir }}/validate/files"
    datamodel_dir: "{{ playbook_dir }}/datamodel"
    raw_report_dir: "{{ playbook_dir }}/validate/reports"
  tasks:
    - name: Prepare validate datamodel directory
      set_fact:
        val_dir: "{{ validate_dir }}/{{ inventory_hostname }}"
      changed_when: False
    - name: Ensure there are no files from previous runs
      file:
        path: "{{ val_dir }}"
        state: absent
      changed_when: False
      run_once: True
    - name: Create directory where assembled validation rule file is stored
      file:
        path: "{{ val_dir }}"
        state: directory
      changed_when: False
      run_once: True
    - name: Prepare reports directory
      file:
        path: "{{ raw_report_dir }}"
        state: directory
      changed_when: False
      run_once: True
- name: Create validation files, based on the datamodel
  hosts: all
  vars:
    datamodel_dir: "{{ playbook_dir }}/datamodel"
  connection: local
  gather_facts: no
  vars_files: [ "{{ datamodel_dir }}/node-model.yml" ]
  roles:
     - validate

- name: Perform automated validation and produce compliance report
  hosts: all
  connection: local
  vars:
    val_dir: "validate/files"
    debug_report_dir: "reports/debug"
    report_dir: "reports"
  tasks:
    - name: Ensure that no report files are present from previous runs
      file:
        path: "{{ report_dir }}"
        state: absent
      changed_when: False
      run_once: True
    - name: Recreate report directory
      file:
        path: "{{ report_dir }}"
        state: directory
      changed_when: False
      run_once: True
    - name: Ensure that no debug report files are present from previous runs
      file:
        path: "{{ debug_report_dir }}"
        state: absent
      changed_when: False
      run_once: True
    - name: Recreate debug report directory
      file:
        path: "{{ debug_report_dir }}"
        state: directory
      run_once: True
    - name: Create Summary Report output directory
      file:
        path: "{{ report_dir }}/{{ inventory_hostname }}"
        state: directory
      changed_when: False
    - name: Use NAPALM to automatically validate configuration
      napalm_validate:
        hostname: "{{ inventory_hostname }}"
        username: "{{ username }}"
        dev_os: "{{ os }}"
        password: "{{ password }}"
        validation_file: "validate/files/{{ inventory_hostname }}/automated-validation.yml"
      register: val_results
      ignore_errors: yes
    - name: Dump results to debug files
      local_action: >
        copy content="{{val_results|to_nice_json}}"
          dest="{{ debug_report_dir }}/{{ inventory_hostname }}-Validation-Compliance-Report.json"
    - name: Render Individual Summary Reports
      template:
        src: "templates/report-validation.j2"
        dest: "{{ report_dir }}/{{ inventory_hostname }}-Summary-Report.txt"
    - name: Remove old compiled summary report
      file:
        path: "{{ report_dir }}/All-Host-Validation-Report.txt"
        state: absent
      run_once: True
    - name: Compile Individual summary reports into single report
      assemble:
        src: "{{ report_dir }}"
        dest: "{{ report_dir }}/All-Host-Validation-Report.txt"
      run_once: True
    - name: Display compliance results
      debug:
        var: val_results.compliance_report.complies
    - name: Compliance check failure
      fail:
        msg: "Checks do not comply against validation rules. Refer to the full report at {{ debug_report_dir }}/{{ inventory_hostname }}-Validation-Compliance-Report.json"
      when: not val_results.compliance_report.complies
