---
- name: Validate interfaces
  hosts: all
  connection: local
  vars:
    interface_val_dir: "{{ playbook_dir }}/validate/interfaces/"
    # Strip the FDQN portion of the hostname off and save it to the hostname variable.
    hostname: "{{ inventory_hostname.split('.')[0] }}"
  tasks:
  - name: Use Napalm to automatically validate LLDP neighbours
    napalm_validate:
      hostname: "{{ inventory_hostname }}"
      username: "{{ username }}"
      dev_os: "{{ os }}"
      password: "{{ password }}"
      validation_file: "{{ interface_val_dir }}/{{ hostname }}.yml"
    register: validation
  - name: "Failed Compliance Report"
    fail:
      msg: "{{ validation.compliance_report|to_nice_json(indent=2)}}"
    when: not validation.compliance_report.complies
  - name: "Compliance report"
    debug:
      msg: "Complies"
    when: validation.compliance_report.complies
    tags: [print_action]
