#
# Create a compliance report from specified template
#
---
- file: path="{{results}}" state=directory
  run_once: true
- template:
    src:  "{{report|default('errors.j2')}}"
    dest: "{{results}}/{{output|default('Non-Compliance.log')}}"
  run_once: true

