---
- name: Get facts
  hosts: all
  connection: local
  gather_facts: no
  tasks:
    - name: get facts from device
      napalm_get_facts:
        hostname: "{{ inventory_hostname }}"
        username: "{{ username }}"
        dev_os: "{{ os }}"
        password: "{{ password }}"
        filter: ['facts','lldp_neighbors_detail']                
      register: napalm_facts
    - name: Print gathered facts
      debug:
        msg: "{{ napalm_facts.ansible_facts|to_nice_json }}"
      tags: [print_action]
