# This playbook gathers interface information across all vendors and saves the output into a YAML file, based on the hostname. 
---
- name: Gather interface facts using NAPALM
  hosts: all
  connection: local
  gather_facts: no
  vars:
    facts: "facts"
    interface_dir: "interfaces"
    # Strip the FDQN portion of the hostname off and save it to the hostname variable.
    hostname: "{{ inventory_hostname.split('.')[0] }}"
  tasks:
     - name: Set global facts, cleanup old files and directories
       set_fact:
          interface_fact_dir: "{{ facts }}/{{ interface_dir }}"
     - name: Checking facts directory is created
       file: path={{ facts }} state=directory
       check_mode: no
       run_once: yes
     - name: Clearing old interfaces fact files
       file: path={{ interface_fact_dir }} state=absent
       changed_when: False
       check_mode: no
     - name: Rebuild interfaces fact directories
       file: path={{ interface_fact_dir }} state=directory
       changed_when: False
       check_mode: no
     - name: Get interfaces from device
       napalm_get_facts:
         hostname: "{{ inventory_hostname }}"
         username: "{{ username }}"
         dev_os: "{{ os }}"
         password: "{{ password }}"
         filter: ['interfaces','interfaces_ip']                
       register: interfaces_facts
       # Saving to YAML
     - copy: content="{{interfaces_facts.ansible_facts|to_nice_yaml(indent=2)}}" dest={{ interface_fact_dir }}/{{ hostname }}.yml
