# This playbook gathers the NTP servers across all vendors and saves the output into a YAML file, based on the hostname. 
---
- name: Gather NTP server facts using NAPALM
  hosts: all
  connection: local
  gather_facts: no
  vars:
    facts: "facts"
    ntp_serv_dir: "ntp_servers"
    # Strip the FDQN portion of the hostname off and save it to the hostname variable.
    hostname: "{{ inventory_hostname.split('.')[0] }}"
  tasks:
     - name: Set global facts, cleanup old files and directories
       set_fact:
          ntp_fact_dir: "{{ facts }}/{{ ntp_serv_dir }}"
     - name: Checking facts directory is created
       file: path={{ facts }} state=directory
       check_mode: no
       run_once: yes
     - name: Clearing old NTP server fact files
       file: path={{ ntp_fact_dir }} state=absent
       changed_when: False
       check_mode: no
     - name: Rebuild NTP server fact directories
       file: path={{ ntp_fact_dir }} state=directory
       changed_when: False
       check_mode: no
     - name: Get NTP servers from device
       napalm_get_facts:
         hostname: "{{ inventory_hostname }}"
         username: "{{ username }}"
         dev_os: "{{ os }}"
         password: "{{ password }}"
         filter: ['ntp_servers']                
       register: ntp_serv_facts
       # Saving to YAML
     - copy: content="{{ntp_serv_facts.ansible_facts|to_nice_yaml(indent=2)}}" dest={{ ntp_fact_dir }}/{{ hostname }}.yml
