# This playbook gathers the usernames across all vendors and saves the output into a YAML file, based on the hostname. 
---
- name: Gather users facts using NAPALM
  hosts: all
  connection: local
  gather_facts: no
  vars:
    facts: "facts"
    users_dir: "users"
    # Strip the FDQN portion of the hostname off and save it to the hostname variable.
    hostname: "{{ inventory_hostname.split('.')[0] }}"
  tasks:
     - name: Set global facts, cleanup old files and directories
       set_fact:
          users_fact_dir: "{{ facts }}/{{ users_dir }}"
     - name: Checking facts directory is created
       file: path={{ facts }} state=directory
       check_mode: no
       run_once: yes
     - name: Clearing users fact files
       file: path={{ users_fact_dir }} state=absent
       changed_when: False
       check_mode: no
     - name: Rebuild users fact directories
       file: path={{ users_fact_dir }} state=directory
       changed_when: False
       check_mode: no
     - name: Get users information from device
       napalm_get_facts:
         hostname: "{{ inventory_hostname }}"
         username: "{{ username }}"
         dev_os: "{{ os }}"
         password: "{{ password }}"
         filter: [ 'users' ]                
       register: users_facts
       # Saving to YAML
     - copy: content="{{users_facts.ansible_facts|to_nice_yaml(indent=2)}}" dest={{ users_fact_dir }}/{{ hostname }}.yml
