# This playbook will gather the running configs from all devices
- name: Get running configs using NAPALM
  hosts: all
  connection: local
  gather_facts: no
  vars:
    results: outputs/configs/running
    hostname: "{{ inventory_hostname.split('.')[0] }}"
  tasks:
    - name: Get running config from device
      napalm_get_facts:
        hostname: "{{ inventory_hostname }}"
        username: "{{ username }}"
        dev_os: "{{ os }}"
        password: "{{ password }}"
        filter: ['config']                
      register: napalm_facts
    - copy: content="{{napalm_facts.ansible_facts['napalm_config']['running']}}" dest={{results}}/{{hostname}}.txt
    - name: Print running config for debugging
      debug:
        msg: "{{ napalm_facts.ansible_facts['napalm_config']['running'] }}"
