# This playbook gathers facts across all vendors and saves the output into a YAML and a JSON file, based on the hostname. 
---
- name: Get facts using NAPALM
  hosts: all
  connection: local
  gather_facts: no
  vars:
    results: outputs/facts
    # Strip the FDQN portion of the hostname off and save it to the hostname variable.
    hostname: "{{ inventory_hostname.split('.')[0] }}"
  tasks:
    - name: Get facts from device
      napalm_get_facts:
        hostname: "{{ inventory_hostname }}"
        username: "{{ username }}"
        dev_os: "{{ os }}"
        password: "{{ password }}"
        filter: ['facts']                
      register: napalm_facts
      # Saving to YAML
    - copy: content="{{napalm_facts.ansible_facts|to_nice_yaml(indent=2)}}" dest={{results}}/{{hostname}}.yml
      # Saving to JSON
    - copy: content="{{napalm_facts.ansible_facts|to_nice_json(indent=2)}}" dest={{results}}/{{hostname}}.json
