- name: Get configs using NAPALM
  hosts: all
  connection: local
  gather_facts: no
  vars:
    results: outputs/configs
    hostname: "{{ inventory_hostname.split('.')[0] }}"
  tasks:
    - name: Get facts from device
      napalm_get_facts:
        hostname: "{{ inventory_hostname }}"
        username: "{{ username }}"
        dev_os: "{{ os }}"
        password: "{{ password }}"
        filter: ['config']                
      register: napalm_facts
    - copy: content="{{napalm_facts.ansible_facts['napalm_config']['running']}}" dest={{results}}/{{hostname}}.txt
    - name: Print gathered IOS facts
      debug:
        msg: "{{ napalm_facts.ansible_facts['napalm_config']['running'] }}"
