---
- name: Building configuration from data model
  hosts: all
  connection: local
  gather_facts: no
  tags: [ 'build','validate' ]
  vars:
      config_dir: "configs"
      build_dir: "compiled"
      hostname: "{{ inventory_hostname.split('.')[0] }}"
  tasks:
     - name: Set global facts, cleanup old files and directories
       set_fact:
          host_dir: "{{ config_dir }}/{{ build_dir }}/{{ hostname }}"
       changed_when: False
       check_mode: yes
     - name: Checking config directory is created
       file: path={{ config_dir }} state=directory
       check_mode: no
       run_once: yes
     - name: Checking build directory is created
       file: path={{ build_dir }} state=directory
       check_mode: no
       run_once: yes
     - name: Clearing old build configuration files
       file: path={{ host_dir }} state=absent
       changed_when: False
       check_mode: no
     - name: Rebuild build configuration directories
       file: path={{ host_dir }} state=directory
       changed_when: False
       check_mode: no

- name: Base configuration
  hosts: all
  connection: local
  tags: [ 'build','validate' ]
  roles:
    - base

- name: Common configuration
  hosts: all
  connection: local
  tags: [ 'build','validate' ]
  roles:
    - common

- name: Interface configuration
  hosts: all
  tags: [ 'build','validate' ]
  connection: local
  roles:
    - interfaces

- name: Routing configuration
  hosts: all
  connection: local
  tags: [ 'build','validate' ]
  roles:
   - routing

- name: Assembling configuration components
  hosts: all
  tags: [ 'build','validate' ]
  tasks:
  - assemble:
     src: "{{ host_dir }}"
     dest: "{{ host_dir }}/assembled.conf"
    changed_when: False

- name: Compare data model with configuration on device, report the differences
  hosts: all
  tags: [ 'validate' ]
  tasks:
  - napalm_install_config:
      hostname: "{{ inventory_hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      dev_os: "{{ os }}"
      config_file: "{{ host_dir }}/assembled.conf"
      replace_config: False
      get_diffs: True
      commit_changes: False
      diff_file: "{{ host_dir }}/config-diff"
      
      
      
